---

- hosts: all
  gather_facts: true
  tasks:
    - name: Grouping!
      group_by:
        key: "{{ ansible_os_family }}"

- hosts: Debian
  gather_facts: false
  serial: 1
  become: yes
  max_fail_percentage: 0
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
      register: aptout
    
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      register: aptupgradeout

        # show the content of aptout var
    - debug: var=aptout
    - debug: var=aptupgradeout

    - name: Create breadcrumb
      file:
        path: "/tmp/patching-crumb-{{ansible_date_time.date}}"
        mode: '0644'
        state: touch
        owner: root
        group: root

    #- name: Output 
    #  shell: "echo {{ aptout }} >> /tmp/patching-crumb-{{ansible_date_time.date}}"

    - name: Copy output of apt update to /tmp/patching-crumb-{{ansible_date_time.date}}
      copy:
        dest: "/tmp/patching-crumb-{{ansible_date_time.date}}"
        content: "{{ aptout.stdout_lines }}"


- hosts: RedHat
  gather_facts: false
  serial: 1
  become: yes
  max_fail_percentage: 0
  tasks:
    - name: Upgrade all packages to the latest version
      yum:
        name: "*"
        state: latest
      register: yumoutput

    - name: Create breadcrumb
      file:
        path: "/tmp/patching-crumb-{{ansible_date_time.date}}"
        mode: '0644'
        state: touch
        owner: root
        group: root
    
    - name: Copy output of yum update to /tmp/patching-crumb-{{ansible_date_time.date}}
      copy:
        dest: "/tmp/patching-crumb-{{ansible_date_time.date}}"
        content: "{{ aptout }}"